/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    NetAdapterCx.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START


#ifndef WDFAPI
#error include wdf.h before netadaptercx.h
#endif

#ifdef NETCX_ADAPTER_2
#error NETCX_ADAPTER_2 previously defined. NETCX_ macro prefix is reserved
#endif


#include <ifdef.h>


#define NETCX_ADAPTER_2
#include <net/extension.h>
#include <net/fragment.h>
#include <net/packet.h>
#include <net/ring.h>
#include <net/ringcollection.h>
#undef NETCX_ADAPTER_2

#include <netadaptercxtypes.h>

#include <netfuncenum.h>


#include <netadapterpacket.h>


#include <nettxqueue.h>
#include <netrxqueue.h>

#include <netdevice.h>
#include <netmemory.h>
#include <netadapter.h>

#include <netpoweroffload.h>
#include <netpoweroffloadlist.h>
#include <netwakesource.h>
#include <netwakesourcelist.h>

#include <netadapteroffload.h>
#include <netadaptertxdemux.h>

#include <netconfiguration.h>
WDF_EXTERN_C_END

