/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    NetAdapterPacket.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START


//
// The structure is similar to NET_PACKET_EXTENSION
// but for query.
//
typedef struct _NET_EXTENSION_QUERY
{
    // Structure fields
    ULONG Size;

    // Extension info fields
    PCWSTR Name;
    ULONG Version;

    NET_EXTENSION_TYPE
        Type;

} NET_EXTENSION_QUERY;

inline
void
NET_EXTENSION_QUERY_INIT(
    _Out_ NET_EXTENSION_QUERY * Extension,
    _In_ PCWSTR Name,
    _In_ ULONG Version,
    _In_ NET_EXTENSION_TYPE Type
)
{
    RtlZeroMemory(Extension, sizeof(NET_EXTENSION_QUERY));
    Extension->Size = sizeof(NET_EXTENSION_QUERY);

    Extension->Name = Name;
    Extension->Version = Version;
    Extension->Type = Type;
}

WDF_EXTERN_C_END

