
#include <d3d12umddi.h>

#pragma region Desktop Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

#ifndef _D3D12COMPILERDDI_H
#define _D3D12COMPILERDDI_H

typedef D3D12DDI_HSTATEOBJECT_0054 D3D12DDI_HCOMPILERSTATEOBJECT;

D3D10DDI_H( D3D12DDI_HCOMPILERDDI )
D3D10DDI_H( D3D12DDI_HCOMPILER )

D3D10DDI_HRT(D3D12DDI_HRTCOMPILERDDI)
D3D10DDI_HRT(D3D12DDI_HRTCOMPILER)
D3D10DDI_HRT(D3D12DDI_HRTCOMPILERCACHESESSION)

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12 Compiler Plugin DDI Release 0, Build rev 1.

#define D3D12DDI_COMPILER_MINOR_VERSION 0
#define D3D12DDI_COMPILER_INTERFACE_VERSION ((D3D12DDI_MAJOR_VERSION << 16) | D3D12DDI_COMPILER_MINOR_VERSION)

#define D3D12DDI_COMPILER_BUILD_VERSION_0001 1
#define D3D12DDI_COMPILER_SUPPORTED_0001 ((((UINT64)D3D12DDI_COMPILER_INTERFACE_VERSION) << 32) | (((UINT64)D3D12DDI_COMPILER_BUILD_VERSION_0001) << 16))

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12 Compiler Plugin DDI Release 0, Build rev 2.
// Change the input of PFND3D12DDI_COMPILER_COMPILE_ADD_TO_STATE_OBJECT and PFND3D12DDI_COMPILER_CALC_PRIVATE_ADD_TO_STATE_OBJECT_SIZE 
// remove dup structs and add defines for the new names

#define D3D12DDI_COMPILER_BUILD_VERSION_0002 2
#define D3D12DDI_COMPILER_SUPPORTED_0002 ((((UINT64)D3D12DDI_COMPILER_INTERFACE_VERSION) << 32) | (((UINT64)D3D12DDI_COMPILER_BUILD_VERSION_0002) << 16))

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12DDI_COMPILER_DDI_FUNCS

typedef VOID (APIENTRY *PFND3D12DDI_COMPILER_DESTROY_DDI)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_GET_SUPPORTED_VERSIONS)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _Inout_ UINT32* puEntries, 
    _Out_writes_opt_( *puEntries ) UINT64* pSupportedPluginDDIVersions
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_SET_SELECTED_VERSION)(
    D3D12DDI_HCOMPILERDDI   hCompilerDDI,
    UINT64                  PluginDDIVersion,
    UINT64                  UsermodeDDIVersion
    );

typedef enum D3D12DDI_COMPILER_TABLE_TYPE
{
    D3D12DDI_COMPILER_TABLE_TYPE_CAPABILITIES = 0, // D3D12DDI_COMPILER_CAPABILITIES_FUNCS
    D3D12DDI_COMPILER_TABLE_TYPE_COMPILER = 1,
} D3D12DDI_COMPILER_TABLE_TYPE;

typedef HRESULT ( APIENTRY * PFND3D12DDI_COMPILER_FILL_DDI_TABLE )(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    D3D12DDI_COMPILER_TABLE_TYPE TableType,
    _Out_writes_bytes_(tableSize) VOID* pTable,
    SIZE_T TableSize
    );

typedef enum D3D12DDI_COMPILER_CALLBACK_TABLE_TYPE
{
    D3D12DDI_COMPILER_CALLBACK_TABLE_TYPE_CACHE = 0,
} D3D12DDI_COMPILER_CALLBACK_TABLE_TYPE;

typedef HRESULT ( APIENTRY * PFND3D12DDI_COMPILER_SET_CALLBACK_DDI_TABLE)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI, 
    D3D12DDI_COMPILER_CALLBACK_TABLE_TYPE TableType, 
    _In_reads_bytes_(TableSize) const void* pTable, 
    SIZE_T TableSize
    );

typedef struct D3D12DDI_COMPILER_DDI_FUNCS
{
    PFND3D12DDI_COMPILER_DESTROY_DDI                        pfnDestroyCompilerDDI;
    PFND3D12DDI_COMPILER_GET_SUPPORTED_VERSIONS             pfnGetSupportedVersions;
    PFND3D12DDI_COMPILER_SET_SELECTED_VERSION               pfnSetSelectedVersion;
    PFND3D12DDI_COMPILER_FILL_DDI_TABLE                     pfnFillDDITable;
    PFND3D12DDI_COMPILER_SET_CALLBACK_DDI_TABLE             pfnSetCallbackDDITable;
} D3D12DDI_COMPILER_DDI_FUNCS;

typedef struct D3D12DDIARG_COMPILER_OPEN_DDI
{
    D3D12DDI_HRTCOMPILERDDI         hRTCompilerDDI;     // in:  Runtime handle
    D3D12DDI_HCOMPILERDDI           hCompilerDDI;       // out: Plugin handle
    D3D12DDI_COMPILER_DDI_FUNCS*    pDDIFuncs;          // out: Plugin function table
} D3D12DDIARG_COMPILER_OPEN_DDI;

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_OPEN_DDI)(
    _Inout_ D3D12DDIARG_COMPILER_OPEN_DDI* pOpenDDIArg
    );

//----------------------------------------------------------------------------------------------------------------------------------
// Common Types

typedef enum D3D12DDI_COMPILER_CACHE_VALUE_TYPE
{
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_OBJECT_CODE        = 0,
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_METADATA           = 1,
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_DEBUG_PDB          = 2,
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_PERFORMANCE_DATA   = 3,

} D3D12DDI_COMPILER_CACHE_VALUE_TYPE;

typedef enum D3D12DDI_COMPILER_VALUE_TYPE_FLAGS
{
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAG_NONE = 0x00000000,
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAG_OBJECT_CODE = (1 << D3D12DDI_COMPILER_CACHE_VALUE_TYPE_OBJECT_CODE),
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAG_METADATA = (1 << D3D12DDI_COMPILER_CACHE_VALUE_TYPE_METADATA),
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAG_DEBUG_PDB = (1 << D3D12DDI_COMPILER_CACHE_VALUE_TYPE_DEBUG_PDB),
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAG_PERFORMANCE_DATA = (1 << D3D12DDI_COMPILER_CACHE_VALUE_TYPE_PERFORMANCE_DATA),

} D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAGS;
DEFINE_ENUM_FLAG_OPERATORS( D3D12DDI_COMPILER_CACHE_VALUE_TYPE_FLAGS )

typedef struct D3D12DDI_COMPILER_ADAPTER_FAMILY
{
    WCHAR szAdapterFamily[128];
} D3D12DDI_COMPILER_ADAPTER_FAMILY;

typedef struct D3D12DDI_COMPILER_TARGET
{
    UINT AdapterFamilyIndex;
    UINT64 ABIVersion;
} D3D12DDI_COMPILER_TARGET;

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12DDI_COMPILER_TABLE_TYPE_CAPABILITIES

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_GET_CAPS)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    _In_ CONST D3D12DDI_APPLICATION_DESC* pApplicationDesc,
    _In_ CONST D3D12DDIARG_GETCAPS* pCaps
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILIES)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    UINT AdapterFamilyIndex,
    _Out_ D3D12DDI_COMPILER_ADAPTER_FAMILY* pAdapterFamily
    );

typedef HRESULT(APIENTRY* PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILY_ABI_VERSIONS)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    UINT AdapterFamilyIndex,
    _Inout_ UINT* pNumABIVersions,
    _Out_writes_opt_(*pNumABIVersions) UINT64* pABIVersions
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILY_COMPILER_VERSION)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    UINT AdapterFamilyIndex,
    _Out_ D3D12DDI_VERSION_NUMBER* pCompilerVersion
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_GET_APPLICATION_PROFILE_VERSION)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    _In_ CONST D3D12DDI_APPLICATION_DESC* pApplicationDesc,
    _Out_ D3D12DDI_VERSION_NUMBER* pApplicationProfileVersion
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_CHECK_FORMAT_SUPPORT)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    DXGI_FORMAT Format,
    _Out_ UINT* pFormatSupport
    );

typedef BOOL (APIENTRY *PFND3D12DDI_COMPILER_CHECK_MULTISAMPLE_QUALITY_LEVELS)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    DXGI_FORMAT Format,
    UINT SampleCount,
    UINT QualityLevel
    );

// D3D12DDI_COMPILER_TABLE_TYPE_CAPABILITIES
typedef struct D3D12DDI_COMPILER_CAPABILITIES_FUNCS
{
    PFND3D12DDI_COMPILER_GET_CAPS                                   pfnGetCaps;
    PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILIES                 pfnEnumerateAdapterFamilies;
    PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILY_ABI_VERSIONS      pfnEnumerateAdapterFamilyABIVersions;
    PFND3D12DDI_COMPILER_ENUMERATE_ADAPTER_FAMILY_COMPILER_VERSION  pfnGetEnumerateAdapterFamilyCompilerVersion;
    PFND3D12DDI_COMPILER_GET_APPLICATION_PROFILE_VERSION            pfnGetApplicationProfileVersion;
    PFND3D12DDI_COMPILER_CHECK_FORMAT_SUPPORT                       pfnCheckFormatSupport;
    PFND3D12DDI_COMPILER_CHECK_MULTISAMPLE_QUALITY_LEVELS           pfnCheckMultisampleQualityLevels;

} D3D12DDI_COMPILER_CAPABILITIES_FUNCS;

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12DDI_COMPILER_CALLBACK_TABLE_TYPE_CACHE

typedef struct D3D12DDI_COMPILER_CACHE_VALUE_KEY
{
    _Field_size_bytes_full_(KeySize) const void* pKey;
    UINT KeySize;
} D3D12DDI_COMPILER_CACHE_VALUE_KEY;

typedef struct D3D12DDI_COMPILER_CACHE_VALUE
{
    _Field_size_bytes_opt_(ValueSize) void* pValue;
    SIZE_T ValueSize;
} D3D12DDI_COMPILER_CACHE_VALUE;

typedef struct D3D12DDI_COMPILER_CACHE_TYPED_VALUE
{
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE  Type;
    D3D12DDI_COMPILER_CACHE_VALUE       Value;
} D3D12DDI_COMPILER_CACHE_TYPED_VALUE;

typedef struct D3D12DDI_COMPILER_CACHE_CONST_VALUE
{
    _Field_size_bytes_opt_(ValueSize) const void* pValue;
    SIZE_T ValueSize;
} D3D12DDI_COMPILER_CACHE_CONST_VALUE;

typedef struct D3D12DDI_COMPILER_CACHE_TYPED_CONST_VALUE
{
    D3D12DDI_COMPILER_CACHE_VALUE_TYPE  Type;
    D3D12DDI_COMPILER_CACHE_CONST_VALUE Value;
} D3D12DDI_COMPILER_CACHE_TYPED_CONST_VALUE;

typedef void* (__stdcall* PFND3D12DDI_COMPILER_ALLOCATION) (
    SIZE_T SizeInBytes,
    _Inout_opt_ void* pContext
    );

typedef HRESULT (APIENTRY CALLBACK *PFND3D12DDI_COMPILER_CACHE_FIND_VALUE_CB)(
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCache,
    _In_ const D3D12DDI_COMPILER_CACHE_VALUE_KEY* pValueKey,
    _Inout_count_(NumValues) D3D12DDI_COMPILER_CACHE_TYPED_VALUE* pValues,
    UINT NumValues,
    _In_opt_ PFND3D12DDI_COMPILER_ALLOCATION pCallbackFunc,
    _Inout_opt_ void* pContext
    );

typedef HRESULT (APIENTRY CALLBACK *PFND3D12DDI_COMPILER_CACHE_STORE_VALUE_CB)(
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCacheSession,
    _In_ const D3D12DDI_COMPILER_CACHE_VALUE_KEY* pValueKey,
    _In_reads_(NumValues) const D3D12DDI_COMPILER_CACHE_TYPED_CONST_VALUE* pValues,
    UINT NumValues
    );

typedef HRESULT (APIENTRY CALLBACK *PFND3D12DDI_COMPILER_CACHE_SET_OBJECT_VALUE_KEYS_CB)(
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCacheSession,
    _In_reads_(NumValueKeys) const D3D12DDI_COMPILER_CACHE_VALUE_KEY* pValueKeys,
    UINT NumValueKeys
    );

typedef struct D3D12DDI_COMPILER_CACHE_CALLBACKS
{
    PFND3D12DDI_COMPILER_CACHE_FIND_VALUE_CB pfnCompilerCacheFindValue;
    PFND3D12DDI_COMPILER_CACHE_STORE_VALUE_CB pfnCompilerCacheStoreValue;
    PFND3D12DDI_COMPILER_CACHE_SET_OBJECT_VALUE_KEYS_CB pfnCompilerCacheSetObjectValueKeys;
} D3D12DDI_COMPILER_CACHE_CALLBACKS;

//----------------------------------------------------------------------------------------------------------------------------------
// D3D12DDI_COMPILER_TABLE_TYPE_COMPILER

typedef struct D3D12DDI_COMPILER_SHADER_DESC
{
    CONST UINT *pShaderCode;
    union
    {
        CONST D3D12DDIARG_STAGE_IO_SIGNATURES *Standard;
        CONST D3D12DDIARG_TESSELLATION_IO_SIGNATURES *Tessellation;
        CONST D3D12DDIARG_MESH_IO_SIGNATURES *Mesh;
    } IOSignatures;
    D3D12DDI_CREATE_SHADER_FLAGS Flags;
    D3D12DDI_SHADERCACHE_HASH ShaderCodeHash;
} D3D12DDI_COMPILER_SHADER_DESC;

typedef struct D3D12DDI_COMPILER_GEOMETRY_SHADER
{
    D3D12DDI_COMPILER_SHADER_DESC Shader;
    CONST D3D12DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY *pOutputStreamDecl;
    UINT NumEntries;
    CONST UINT *BufferStridesInBytes;
    UINT NumStrides;
    UINT RasterizedStream;
} D3D12DDI_COMPILER_GEOMETRY_SHADER;

typedef D3D12DDI_BLEND_DESC D3D12DDI_COMPILER_BLEND_DESC;

typedef D3D12DDIARG_CREATEELEMENTLAYOUT D3D12DDI_COMPILER_ELEMENTLAYOUT_DESC;

typedef D3D12DDIARG_CREATE_ROOT_SIGNATURE_0100 D3D12DDI_COMPILER_ROOT_SIGNATURE_DESC;

typedef struct D3D12DDI_COMPILER_RASTERIZER_DESC
{
    D3D12DDI_FILL_MODE FillMode;
    D3D12DDI_CULL_MODE CullMode;
    BOOL FrontCounterClockwise;
    FLOAT DepthBias;
    FLOAT DepthBiasClamp;
    FLOAT SlopeScaledDepthBias;
    BOOL DepthClipEnable;
    BOOL ScissorEnable;
    D3D12DDI_LINE_RASTERIZATION_MODE LineRasterizationMode;
    UINT ForcedSampleCount;
    D3D12DDI_CONSERVATIVE_RASTERIZATION_MODE ConservativeRasterizationMode;
} D3D12DDI_COMPILER_RASTERIZER_DESC;

typedef struct D3D12DDI_COMPILER_DEPTH_STENCIL_DESC
{
    BOOL DepthEnable;
    D3D12DDI_DEPTH_WRITE_MASK DepthWriteMask;
    D3D12DDI_COMPARISON_FUNC DepthFunc;
    BOOL StencilEnable;
    BOOL FrontEnable;
    BOOL BackEnable;
    UINT8 FrontFaceStencilReadMask;
    UINT8 FrontFaceStencilWriteMask;
    D3D12DDI_DEPTH_STENCILOP_DESC FrontFace;
    D3D12DDI_DEPTH_STENCILOP_DESC BackFace;
    BOOL DepthBoundsTestEnable;
    UINT8 BackFaceStencilReadMask;
    UINT8 BackFaceStencilWriteMask;
} D3D12DDI_COMPILER_DEPTH_STENCIL_DESC;

typedef D3D12DDI_VIEW_INSTANCING_DESC D3D12DDI_COMPILER_VIEW_INSTANCING_DESC;

typedef struct D3D12DDIARG_COMPILER_COMPILE_PIPELINE_STATE
{
    D3D12DDI_COMPILER_SHADER_DESC *pComputeShader;
    D3D12DDI_COMPILER_SHADER_DESC *pVertexShader;
    D3D12DDI_COMPILER_SHADER_DESC *pPixelShader;
    D3D12DDI_COMPILER_SHADER_DESC *pDomainShader;
    D3D12DDI_COMPILER_SHADER_DESC *pHullShader;
    D3D12DDI_COMPILER_GEOMETRY_SHADER *pGeometryShader;
    D3D12DDI_COMPILER_ROOT_SIGNATURE_DESC *pRootSignature;
    D3D12DDI_COMPILER_BLEND_DESC *pBlendState;
    UINT SampleMask;
    D3D12DDI_COMPILER_RASTERIZER_DESC *pRasterizerState;
    D3D12DDI_COMPILER_DEPTH_STENCIL_DESC *pDepthStencilState;
    D3D12DDI_COMPILER_ELEMENTLAYOUT_DESC *pElementLayout;
    D3D12DDI_INDEX_BUFFER_STRIP_CUT_VALUE IBStripCutValue;
    D3D12DDI_PRIMITIVE_TOPOLOGY_TYPE PrimitiveTopologyType;
    UINT NumRenderTargets;
    DXGI_FORMAT RTVFormats[8];
    DXGI_FORMAT DSVFormat;
    DXGI_SAMPLE_DESC SampleDesc;
    D3D12DDI_COMPILER_VIEW_INSTANCING_DESC ViewInstancingDesc;
    D3D12DDI_COMPILER_SHADER_DESC *pMeshShader;
    D3D12DDI_COMPILER_SHADER_DESC *pAmplificationShader;
} D3D12DDIARG_COMPILER_COMPILE_PIPELINE_STATE;

typedef SIZE_T (APIENTRY *PFND3D12DDI_COMPILER_CALC_PRIVATE_COMPILER_SIZE)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    _In_ CONST D3D12DDI_APPLICATION_DESC* pApplicationDesc
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_CREATE_COMPILER)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    _In_ CONST D3D12DDI_COMPILER_TARGET* pTarget,
    _In_ CONST D3D12DDI_APPLICATION_DESC* pApplicationDesc,
    D3D12DDI_HCOMPILER hCompiler,
    D3D12DDI_HRTCOMPILER hRTCompiler
    );

typedef VOID (APIENTRY *PFND3D12DDI_COMPILER_DESTROY_COMPILER)(
    D3D12DDI_HCOMPILERDDI hCompilerDDI,
    D3D12DDI_HCOMPILER hCompiler
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_COMPILE_PIPELINE_STATE)(
    D3D12DDI_HCOMPILER hCompiler,
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCacheSession,
    D3D12DDI_COMPILER_VALUE_TYPE_FLAGS ValueTypeFlags,
    CONST D3D12DDIARG_COMPILER_COMPILE_PIPELINE_STATE* pPipelineStateArg
    );

typedef SIZE_T (APIENTRY *PFND3D12DDI_COMPILER_CALC_PRIVATE_STATE_OBJECT_SIZE)(
    D3D12DDI_HCOMPILER hCompiler,
    _In_ CONST D3D12DDIARG_CREATE_STATE_OBJECT_0054* pCreateStateObject
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_COMPILE_CREATE_STATE_OBJECT)(
    D3D12DDI_HCOMPILER hCompiler,
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCacheSession,
    D3D12DDI_COMPILER_VALUE_TYPE_FLAGS ValueTypeFlags,
    _In_ CONST D3D12DDIARG_CREATE_STATE_OBJECT_0054* pCreateStateObject,
    D3D12DDI_HCOMPILERSTATEOBJECT hStateObject
    );

typedef SIZE_T (APIENTRY *PFND3D12DDI_COMPILER_CALC_PRIVATE_ADD_TO_STATE_OBJECT_SIZE)(
    D3D12DDI_HCOMPILER hCompiler,
    _In_ CONST D3D12DDIARG_ADD_TO_STATE_OBJECT_0072* pAddToStateObject
    );

typedef HRESULT (APIENTRY *PFND3D12DDI_COMPILER_COMPILE_ADD_TO_STATE_OBJECT)(
    D3D12DDI_HCOMPILER hCompiler,
    D3D12DDI_HRTCOMPILERCACHESESSION hrtCompilerCacheSession,
    D3D12DDI_COMPILER_VALUE_TYPE_FLAGS ValueTypeFlags,
    _In_ CONST D3D12DDIARG_ADD_TO_STATE_OBJECT_0072* pAddToStateObject,
    D3D12DDI_HCOMPILERSTATEOBJECT hStateObject
    );

typedef VOID ( APIENTRY* PFND3D12DDI_COMPILER_DESTROY_STATE_OBJECT )(
    D3D12DDI_HCOMPILER hCompiler,
    D3D12DDI_HCOMPILERSTATEOBJECT hStateObject
    );

// D3D12DDI_COMPILER_TABLE_TYPE_COMPILER
typedef struct D3D12DDI_COMPILER_FUNCS
{
    PFND3D12DDI_COMPILER_CALC_PRIVATE_COMPILER_SIZE             pfnCalcPrivateCompilerSize;
    PFND3D12DDI_COMPILER_CREATE_COMPILER                        pfnCreateCompiler;
    PFND3D12DDI_COMPILER_DESTROY_COMPILER                       pfnDestroyCompiler;
    PFND3D12DDI_COMPILER_COMPILE_PIPELINE_STATE                 pfnCompilePipelineState;
    PFND3D12DDI_COMPILER_CALC_PRIVATE_STATE_OBJECT_SIZE         pfnCalcPrivateStateObjectSize;
    PFND3D12DDI_COMPILER_COMPILE_CREATE_STATE_OBJECT            pfnCompileCreateStateObject;
    PFND3D12DDI_COMPILER_CALC_PRIVATE_ADD_TO_STATE_OBJECT_SIZE  pfnCalcPrivateAddToStateObjectSize;
    PFND3D12DDI_COMPILER_COMPILE_ADD_TO_STATE_OBJECT            pfnCompileAddToStateObject;
    PFND3D12DDI_COMPILER_DESTROY_STATE_OBJECT                   pfnDestroyStateObject;
} D3D12DDI_COMPILER_FUNCS;

#endif /*_D3D12COMPILERDDI_H*/

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */
#pragma endregion

#ifndef _D3D12COMPILERDDI_H
#define _D3D12COMPILERDDI_H

#endif // _D3D12COMPILERDDI_H

